// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNMA4uNBrkmzzHUgiRBjnpPqHz3vgrERE',
    appId: '1:57393701214:web:531c1d82931c7f9293efcf',
    messagingSenderId: '57393701214',
    projectId: 'gps-app-2-c781f',
    authDomain: 'gps-app-2-c781f.firebaseapp.com',
    storageBucket: 'gps-app-2-c781f.appspot.com',
    measurementId: 'G-KY049M1JKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBYfHvB5n8n4El3gPiS8wZxqSaXYK-mDs',
    appId: '1:57393701214:android:525f3a5b5f553ac093efcf',
    messagingSenderId: '57393701214',
    projectId: 'gps-app-2-c781f',
    storageBucket: 'gps-app-2-c781f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIHZUdfXoKrEap7qjshlawpNt-ki9vkdU',
    appId: '1:57393701214:ios:6234feb2007f6b2493efcf',
    messagingSenderId: '57393701214',
    projectId: 'gps-app-2-c781f',
    storageBucket: 'gps-app-2-c781f.appspot.com',
    iosBundleId: 'com.example.gpsapp3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIHZUdfXoKrEap7qjshlawpNt-ki9vkdU',
    appId: '1:57393701214:ios:6234feb2007f6b2493efcf',
    messagingSenderId: '57393701214',
    projectId: 'gps-app-2-c781f',
    storageBucket: 'gps-app-2-c781f.appspot.com',
    iosBundleId: 'com.example.gpsapp3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNMA4uNBrkmzzHUgiRBjnpPqHz3vgrERE',
    appId: '1:57393701214:web:b08a66ece9248d9793efcf',
    messagingSenderId: '57393701214',
    projectId: 'gps-app-2-c781f',
    authDomain: 'gps-app-2-c781f.firebaseapp.com',
    storageBucket: 'gps-app-2-c781f.appspot.com',
    measurementId: 'G-DPF3BD4N4M',
  );

}